jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # serverTimezone: ??
    # elideSetAutoCommits: JDBC Client?? setAutoCommit()? ??? ??? MySQL ??? SET autocommit = ? ??? ????? setAutoCommit() ???? MySQL ??? autocommit ?? ???? ?? ??
    # autoReconnect: MySQL ????? ???? ???(?? 8??) ???? ??? ?? ??, ??? ??? ?? ???? ??? ???? ?? ???? ??? ?? ?? ? ???? ?? ?? ??
    url: jdbc:mysql://127.0.0.1/3306/react_board?useTimezone=true&serverTimezone=UTF&elideSetAutoCommits=true&autoReconnect=true
    username: ENC(aXl4VrqBYJLcjYIR36J23w==)
    password: ENC(Js2u5d8JhiiSsyF+dV1QlT76Gp54166g)
  servlet:
    multipart:
      max-file-size: 100MB # ???? ?? ??? ??
      max-request-size: 110MB # ??? ?? ??? ??(???? ?? ???? ?? ?)
